### ISSUE TITLE
Something very odd happened while running slendr

### ISSUE THREAD

**Issue by jaurbanChicago** [bodkan/slendr#82]
Hello Martin, 
Hope that you are doing well!! Something extremely weird happened when I was running slendr and I set up the flag `overwrite=TRUE` in compile-model, everything in my directory got removed, every single file :/. I think this might be a bug in the flag. Here´s a screenshot so that you can see:
![Screen Shot 2022-03-04 at 12 21 03 PM](https://user-images.githubusercontent.com/90297093/156819959-85b3097e-50e8-4c2c-9f57-c6fb17798750.png)

Even the .Rmd file where I was writing the script got deleted from the computer haha :(. 

Best, 
Toño

**Comment by jaurbanChicago** [comment]
The .Rmd file suddenly closed, so I checked my directory and that´s when I saw that everything in my directory got deleted

**Comment by bhaller** [comment]
Yikes.  @bodkan, FYI, best practice when overwriting stuff is to move the old stuff aside to a temporary position (i.e., rename the whole folder to a randomly generated filename like `.016824382`), write out all the new stuff, confirm that it exists (i.e., the write succeeded), and then and only then, delete the old stuff from the temporary place you moved it to.  It's a hassle, but avoids this sort of thing...

**Comment by jaurbanChicago** [comment]
Yes, thank you for the tip @bhaller ! I know better for next time!

**Comment by bhaller** [comment]
> Yes, thank you for the tip @bhaller ! I know better for next time!

Hi @jaurbanChicago!  No, my comment was intended for Martin; I'm saying `slendr` ought to do that, end users shouldn't have to worry about such things.  :->

**Comment by jaurbanChicago** [comment]
Ahhhhhh I see! Thanks!

**Comment by bodkan** [comment]
The `overwrite = ` argument of `compile()` is always set to `FALSE` by default and the user must explicitly (and willingly) set it to `TRUE` in order to make any dramatic changes.

If the flag remains `overwrite = FALSE` (again, it's the default because this is the safe thing to do), compilation of a model fails.

If the user sets it to `overwrite = TRUE`, this is interpreted as an instruction to overwrite the directory because a new model should be compiled in it.

To me this follows the difference between `rm` and `rm -f`? It's not like I'm deleting anything without the user's knowledge.

I was fairly sure the interface is conservative and safe. Nothing makes a potentially destructive unless the user requests it.

I'm very sorry this caused problems, @jaurbanChicago!

**Comment by bodkan** [comment]
What I will do is make `compile()` ask _"Are you really sure you want to do this?"_

Then again, people often click "Yes" without really thinking, so this pushes a potential disaster only one step further.

**Comment by bodkan** [comment]
I will also prevent compilation into a directory which contains more stuff than just (what looks like) slendr config files.

**Comment by jaurbanChicago** [comment]
Hello @bodkan , 

Yes, I think that I misunderstood the flag. I thought it was going to overwrite just the slendr-related files and not the entire directory. I promise I´ll be more careful with overwrite flags from now on!
Best, 

Toño @jaurbanChicago

**Comment by bodkan** [comment]
Note to self: for each slendr model, I actually know exactly which (and how many -- there can be many individual raster maps!) configuration files are in the model directory because each model carries a [table of checksums with it](https://github.com/bodkan/slendr/blob/43716f756dbdb69cf91f4135b1fd3d92cac89282/R/compilation.R#L196).

This can be used with `overwrite = TRUE` to avoid even the unlikeliest of disasters.

I still think what slendr did here is consistent with the interface and documentation, but I should try to prevent as many disasters as possible -- even those which on the face of it look like exactly what slendr what asked to do. :(

**Comment by jaurbanChicago** [comment]
Hahahaha yea, fair point. I am so sorry I caused this problem, I should have read the instructions more carefully!

**Comment by bodkan** [comment]
WHAT?! Why are _you_ apologizing to _me_? That's not how this works. ;) Thank you for making me realize that potentially destructive operations such as deleting files, even if they are documented as such and explicitly switched off, can never be presented with careful enough interface.

(Especially if I'm selling slendr as a simulation library not just for advanced SLiM users interested in spatial popgen, but also for complete novices to simulations in general.)

**Comment by petrelharp** [comment]
Here's my suggestion: change the behavior so that `overwrite=TRUE` doesn't delete the directory, it just doesn't complain that the directory already exists, and overwrites any files it needs to. To do this, I think you'd just remove [this line](https://github.com/bodkan/slendr/blob/d1fef5adc27a091bc137071c672e6976ae250b47/R/compilation.R#L93). This would mean that if someone compiles, then changes the model, and compiles again, they might end up with some unnecessary files in the directory, but they can always go `rm -rf` themselves. 

I think this would be even better than removing the files in the checksum table, since if compilation fails then the files won't be removed (ie they won't be removed until they're ovewritten).

**Comment by bodkan** [comment]
Hey, thanks for the suggestion, Peter. Sorry to be late here!

I did consider that option but ultimately decided against it. The reason is that unless the path for a tree-sequence output file is explicitly given, slendr saves the output into the model directory by default. Maybe that turns out to be not the right decision going forward but it has been extremely convenient so far, not having to keep track of output files. I.e., being able to say `ts_load(model)` rather than `ts_load(model, file = <...>)`.

This simpler solution would mean that a tree sequence file in a given directory could easily get out of sync with the model config files in that directory. 🤔

So what I implemented instead is the following.

- If the user calls `compile_model(..., path = "path/to/directory")` in an interactive console and `"path/to/directory"` exists, slendr complains about a non-empty directory being in the way (that has been the behavior so far).
- If the user calls `compile_model(..., path = "path/to/directory", overwrite = TRUE)` in an interactive console and `"path/to/directory"` exists, slendr complains about a non-empty directory being in the way **and very loudly asks the user to confirm that the directory should be deleted like seriously I'm not kidding are you sure this is what you want buddy** (not just config files, but outputs too). This is done with the standard [interactive R menu](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/menu.html).
- Because the R interactive menu fails in non-interactive R sessions (R scripts being run in the terminal etc), calling `compile_model(..., path = "path/to/directory", overwrite = TRUE)` still fails with an error, complaining about a non-empty directory being in the way. If the user wants to overwrite a directory in a non-interactive mode, the have to add `force = TRUE` and run `compile_model(..., path = "path/to/directory", overwrite = TRUE, force = TRUE)`.

In other words, there is now one additional failsafe mechanism (manual confirmation menu in interactive R sessions and `force = TRUE` which works in non-interactive script modes).

I think this is as safe as I can currently make it.

Also, one thing that I should advertise more is that `compile_model()` does not require a manually specified model directory anymore. If no directory is given, a `tempdir()` is called and used. I added this option because I got tired by having to always specify the path to config files in the interactive mode (this gets annoying because in 99.9% of the cases I don't care about the location of those plain text files and raster maps, this are low-level details that the user shouldn't have to concern themselves with during model development). This is why I implemented this `overwrite = TRUE` stuff in the first place.

Hopefully with all this we're getting the best of both worlds.

This essay is now over. :) Just wanted to archive all this in case it comes up in the future again.
