### ISSUE TITLE
slim call throws conversion error

### ISSUE THREAD

**Issue by percyfal** [bodkan/slendr#87]
Hi,

I'm testing slendr version 0.1.0 and to try it out I have based my first model on the documentation example (out-of-Africa), copy-pasting the code. The [slim call](https://www.slendr.net/index.html#7-run-the-model-in-slim) throws the following error:
```r
slim(model, sequence_length = 10e6, recombination_rate = 1e-8,
     save_locations = TRUE, method = "batch", random_seed = 314159)
Error: Can't convert from <double> to <logical> due to loss of precision.
...
```
The error originates in [utils.R::process_sampling](https://github.com/bodkan/slendr/blob/main/R/utils.R#L427) when replacing NA's for -1 in the `processed_schedule` tibble. I temporarily solved this by converting the tibble to a data frame and then back:

```r
x <- as.data.frame(processed_schedule)
x <- replace(x, is.na(x), -1)
processed_schedule <- tibble(x)
```

I'm running tibble version 3.1.2 in case this actually is a change in behaviour of a dependency.

**Comment by bodkan** [comment]
Thanks for reporting the issue and even more for digging into the code to check where the problem originates!

Given that I haven’t found this in my unit tests, I do wonder if this is due to a change in some tibble defaults, just as you suspect yourself. I’m not sure which tibble I’m running (on the phone right now), but I’m guessing it’s the latest 3.1.6. Regardless, the code should be robust to such tiny things.

Could you please paste here a minimum but complete example script that leads to the error? I would then use it to

- make the code more robust (perhaps by literally implementing your workaround)
- include it in the unit tests somehow, to make sure this doesn’t happen again.

Thank again you for your help!

**Comment by bodkan** [comment]
Ah, wait. Just read what you wrote again and see that you ran the code from the first tutorial literally? In that case I will first check to see if the tibble version could be behind this.

**Comment by bodkan** [comment]
In this case, maybe performing the replacement on the base data frame is the best course of action, just as you did. Maybe the base `replace` has some strange interaction with the tibble.

Still, I want to understand where does the error come from exactly, especially given that my unit tests and automatic vignette rendering pipeline has never bumped into this problem.

I will take a closer look tomorrow.

**Comment by percyfal** [comment]
Hi, updating to tibble=3.1.6 solves it! I just glanced quickly at the [tibble changelog](https://tibble.tidyverse.org/news/index.html) but I'm uncertain in which version the behaviour changed. Anyhow, sorry for the noise and thanks for a great package!

**Comment by bodkan** [comment]
That's great news!

A bit annoying that we don't know what exactly changed. I don't see anything glaringly obvious in the changelog either. I have iterated over several versions of tidyverse dependencies over the past year, tibble included. I suspect there was perhaps a bug in some NA handling defaults? I guess we'll never know.

Thank you for reporting back and for verifying that things work with the latest tibble version! If a similar issue comes up, I'll redirect the users here.
