### ISSUE TITLE
A few assorted usage issues: installation, visualization, distance units

### ISSUE THREAD

**Issue by ornobalam** [bodkan/slendr#92]
Hi! 

I've been trying to use slendr to create a spatial model of rice domestication and post-domestication spread. In the process, I've run into several issues, many of which are probably things I am doing wrong. I considered opening three or four different issues, but eventually decided to post them all together here. Please let me know if you would prefer opening multiple individual issues in the future.

1. Whenever I try to load slendr from a new R session, I get the following error:
Error: .onLoad failed in loadNamespace() for 'slendr', details:
  call: py_module_import(module, convert = convert)
  error: ModuleNotFoundError: No module named 'tskit'

I then have to remove slendr, clear the environment, reinstall it, and run setup_env() again to get it working. The way to prevent the error in the first place is to run clear_env() before I close an R session. This way, slendr loads fine when I start a new session, but I have to run setup_env() again. This is not a huge problem for me, just thought you might want to know.

2. When visualizing exponential growth, it always looks something like this:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/55851720/167310788-a482cc6d-df0a-438c-809c-856edf1c3f0a.png">

In all of these populations, exponential growth ends at least 2000 years ago, but the visualization implies that they have grown exponentially till today. Visualization really is a luxury, so I am not complaining either way, but just wanted to point it out.

3. I am a little unclear on the distance units for spatial competition and mating in compile_model(). I am using EPSG:4326. When specifying radii for population ranges, it seems the units are in meters (mine are about 500e3). But when specifying competition or mating distance, I can only provide distances of up to about 10. I am assuming this is in lat/lon coordinates?

(PS: I had another issue that I was able to resolve quite easily, so I removed that.)

**Comment by bodkan** [comment]
Hello @ornobalam, sorry for the slow response. I've been super swamped in the last couple of weeks and I'm also knee deep in some [internal slendr refactoring](https://github.com/bodkan/slendr/pull/91) so I will have to take a closer look at your 2 and 3 items later this week. I hope that's OK. I'll do my best to reply as soon as I can.


As for item number 1, would you mind taking a look at the couple of quick notes I wrote [here](https://github.com/bodkan/slendr/issues/93) and continue conversation there?

I have seen this error happen from time to time and in 100% of cases it was either due to a problem with one particular RStudio setting or with something else activating a different Python environment **before** slendr can activate its own. Unfortunately, only one Python env can be active in the lifetime of an R session and there's nothing that slendr can do about it. This is a limitation on R-Python interoperation layer, outside of slendr's hands.

If you could reply with your own answers to the items I wrote there, I would appreciate it.

Thanks!

I will be back with an answer to your other issues soon.

**Comment by ornobalam** [comment]
No worries, and no rush at all! I will continue the conversation on the first issue in the thread you linked to.

**Comment by bodkan** [comment]
Hmm, this issue slipped through. @ornobalam Is this still something that needs to be fixed? If it is, could you let me know which of the issues still persist? Thanks.

**Comment by ornobalam** [comment]
Hi! Issue (1) was resolved. (3) I've dealt with just by using EPSG:3035 as in the tutorials. (2), which is the visualization issue, depends on how precise you want to be. Right now, I think if you have a model where there is a continuous expansion from 3000 to 2000 generations ago and then a constant population size for the last 2000 generations, it is not apparent in the visualization. It just looks like an expansion till the present day.

**Comment by bodkan** [comment]
Thanks!

Wrt (2), could you please a tiny tiny R script demonstrating the issue with plot_model?

**Comment by ornobalam** [comment]
Hi! I have attached an R script. I hope it's helpful!

**Comment by ornobalam** [comment]
I couldn't attach the script here for some reason, so I sent it via email. Let me know if the attachment didn't work!

**Comment by bodkan** [comment]
Hello, I'm afraid I don't see the script anywhere, not even in my email.

Can you maybe just paste it within the ``` and ``` Markdown tags? Or simply paste it here as a text.

Thanks!

**Comment by ornobalam** [comment]
Ah okay! Here it is:

`library(tidyverse)
library(slendr)

# Model 1 demonstrating the issue I mentioned

mainland = population("mainland",parent = "ancestor",time = 8001, N = 2000)

island = population(
  "island", parent = mainland, time = 4500, N = 50
) %>% resize(N = 2000,time = 4000,end = 3000,how = "exponential")

# As exponential growth ends 3000 generations ago, it's implicit that the population size 
# remains constant after that (unless I am wrong about this)

model_dir <- paste0(tempfile(), "model1")

model1 <- compile_model(
  populations = list(mainland,island),
  generation_time = 1,
  path = model_dir,
  direction = "backward"
)

plot_model(model1)

# Model 2, showing how the issue can be resolved by explicitly adding another resize function
# for the island population


# mainland is the same

island2 = population(
  "island2", parent = mainland, time = 4500, N = 50
) %>% resize(N = 2000,time = 4000,end = 3000,how = "exponential") %>% 
  resize(N= 2000, time = 3000,how="step")

# This adjustment probably shouldn't have to be made?

model_dir_2 <- paste0(tempfile(), "model2")

model2 <- compile_model(
  populations = list(mainland,island2),
  generation_time = 1,
  path = model_dir_2,
  direction = "backward"
)

plot_model(model2)
`

**Comment by bodkan** [comment]
Completely dropped the ball on this one!

The code in the bugreport comes from an old version of slendr so this can't be reproduced anymore... however, the same visualization issue popped up elsewhere and has been (I'd hope) fixed not too much later after this issue has been filed.

If someone else encounters this -- it turned out to be purely a visualization issue caused by a bug in `plot_model()`. The simulations themselves did proceed correctly.
