### ISSUE TITLE
Admixture in slendr vs msprime

### ISSUE THREAD

**Issue by archgen** [bodkan/slendr#99]
Hi Martin,

I just have a question regarding the simulation of admixture in slendr and how that translates to/relates to msprime (transferring my msprime model to slendr). 

In msprime, admixture (the movement of proportion p lineages from one population to another) is handled by the add_mass_migration() parameter, where a proportion of lineages, p, will migrate from source to destination (backwards in time) in generation time, t. Because this parameter does not alter the migration rates between populations, the add_migration_rate_change() can be provided to ensure no migration continues after the simulated pulse(mass) migration.

Q: How does the slendr function gene_flow() simulate the rate parameter in relation to the start and end parameters? I.e. is this the proportion of lineages that migrate from source (from) to destination (to) "each generation" over the start and end periods (basically continuous migration of rate defined each generation)? Or is it the total proportion of lineages that will migrate over the start and end periods? 
As an example how do the following set-ups differ in the way slendr models admixture? 

gene_flow(from=P1, to=P2, rate=0.5, start=10, end=5) VS gene_flow(from=P1, to=P2, rate=0.5, start=10, end=9). 

Similarly, in msprime, the formation of an admixed population is performed through the function 
(example) = add_admixture(time=15, derived=P3, ancestral=[P2,P1], proportions=[0.5,0.5]) 

such that 50% of the lineages from P3 migrate to P2 and P1, respectively, (backwards in time). To carry-out the same behaviour in slendr, would you define the P3 population as follows: 
population(name=“P3”, time=15, parent=P2) 
and then simulate admixture at the time of P3's formation as follows: 
gene_flow(from=P1, to=P3, rate=0.5, start=15, end=16), # Note P3 parent population is modelled as P2? 

I hope my questions are clear and please ask me to clarify if required! 

Thanks very much for your help.

Best,
Matthew

**Comment by bodkan** [comment]
Hello Matthew,

Thanks again for being interested in slendr.

If I understand your question # 1 correctly, the difference between (from your message)

```
gene_flow(from=P1, to=P2, rate=0.5, start=10, end=5)
```

and 

```
gene_flow(from=P1, to=P2, rate=0.5, start=10, end=9)
```

is that in the former, slendr will "spread out" the migration between generation 10 and 5 so that the total P1 ancestry in P2 will be ~50%. In the latter case, the same will happen but the ~50% P1 ancestry in P2 will be simulated only over the course of a single generation.

Does this make sense?

Actually, now that I'm looking at that... maybe `rate=?` is not the right word? Should this be `proportion=` instead? Asking as a non-native speaker. :)

--

As for question 2, if I were to form an 50-50 mixture population in slendr (like your P3), I would do exactly what you propose.

--

I'm not much of an msprime person (I wrote exactly one msprime script in the last ~4 years and that's the msprime script that's built into slendr :)) so I honestly wasn't aware of all these options. The slendr interface is closely modelled by SLiM semantics because slendr *was* SLiM-only for about 70% of the time of its existence (msprime option was added only very late in its development), which is why the options are perhaps a bit more limited compared to the full msprime. Or maybe not limited in function, as you *can* definitely program these things, but perhaps needing one or two extra lines of code.

--

If you'd like to see how gene flow is implemented in the msprime backend, [these couple of lines](https://github.com/bodkan/slendr/blob/b2bafb631b5fce2ebf4cea5a2153a4fe287ea678/inst/scripts/script.py#L167) should clarify that. That block of code with the for loop essentially iterates of a data frame object with all gene-flow events specified by slendr in R using its `gene_flow()` function and schedules the msprime migration events appropriately.

**Comment by bodkan** [comment]
Closing because it seems that the questions have been answered. Please reopen in case an issue/bug comes up related to this.

**Comment by bodkan** [comment]
Hello Yann! Thanks for checking out slendr! I've recently re-read your review on population genomics methods in preparation for a course I have to put together. 🤓 

> Thank you so much for creating this resource, for the beautiful vignettes, and the detailed, informative Github. If all bioinformatic tools were designed like this, the entire community would be ten years ahead at least.

Wow, thank you so much for the kind words. It means a lot. Particularly because I'm _not_ personally very satisfied with the state of the vignettes. 😬 Every single vignette was written very much in haste, in parallel as I was developing code for every respective topic that is discussed therein (often very obviously in a "just thinking out loud here" style)... and I never found the time to go back to the vignettes to edit them and polish them. I always worry they much less useful than what a casual glance might suggest. Anyway, I'm happy you found the documentation useful despite me being so self-conscious about it!

---

With regards to your issue and question. I'm embarrassed to say that you're right about the potential confusion around the `rate =` parameter. I've been aware of it for a long while at this point.

When I put the `gene_flow()` function together for the first time, years ago, I always thought about encoding the total aggregate amount of ancestry that moves over given time window. Honestly, I can't quite remember why I didn't call this parameter `proportion =`. ¯\\\_(ツ)\_/¯ I want to say this is either a small English language goof on my part, or maybe I simply took over the name of the corresponding SLiM function. This might perhaps make sense because--and this is something nobody outside of the circle of my immediate collaborators back then knows--for the first ~1.5 years of slendr's existence, it was an exclusively SLiM-based package. I added msprime support only very late, when I realized I accidentally built a simulation interface which is much more general. :) And a lot of decisions I'd made until that point remained the way they are.

Anyway, long story short, I completely agree with you on that confusion. Every time I teach simulations using slendr, it gives me a pause... 😬

I've been thinking about how to fix this. I just put out a a preprint about [a new software](https://www.biorxiv.org/content/10.64898/2025.12.18.694482v1) which uses slendr heavily. My idea was, as soon as that paper is in review, I'd start working on a slendr 2.0 release, in which I'd like to clean up a couple of things I've grown to dislike about slendr, even at the price of minor breaks in compatibility.

In the context of this issue in particular, I'm thinking about introducing a new parameter called `proportion =`, which will function in the same way as the `rate =` parameter right now. At the same time, I'd have slendr issue a "future deprecation warning" message (just like other R packages do, in situations like this), informing users they should use this new parameter instead (but still have `rate =` stick around the way it does now so that everybody's code continues to work unchanged). Then, the moment 2.0 would roll out (whenever that would happen), the deprecation would go into effect, and I would (re)introduce a new" `rate =` parameter too, behaving just the way one would expect for something called "a rate (per unit of time)".

No harm should be done either way, because I would also introduce the sanity check so that "rate above 100% ancestry" cannot happen. So, only minor annoyance at worst.

---

I hope this explanation makes some sense. Please do let me know if it doesn't!

As I said, it's one of the problems I've been aware for some time now and something I've been brewing my thoughts over in the back of my mind. It's always great to have more eyes on (any) software and to get feedback, so thanks so much again for letting me know what you think and for reporting the issue. 

Have a great winter break!

**Comment by bhaller** [comment]
Hi @bodkan!  My one comment here:

> In the context of this issue in particular, I'm thinking about introducing a new parameter called `proportion =`, which will function in the same way as the `rate =` parameter right now. At the same time, I'd have slendr issue a "future deprecation warning" message (just like other R packages do, in situations like this), informing users they should use this new parameter instead (but still have `rate =` stick around the way it does now so that everybody's code continues to work unchanged). Then, the moment 2.0 would roll out (whenever that would happen), the deprecation would go into effect, and I would (re)introduce a new" `rate =` parameter too, behaving just the way one would expect for something called "a rate (per unit of time)".

Keep in mind that many users don't keep current with new versions, and when they do update they jump ahead by many versions at once.  So if you (1) have a `rate=` parameter (the state now), (2) deprecate the old `rate=` and then, soon thereafter, (3) introduce a new `rate=`, you will have users upgrading directly from (1) to (3) who will never see the deprecation warning, and whose code will change in behavior from the old `rate=` to the new `rate=` without warning.  Do you have a plan for how that can be detected and still issue a warning (or, I would say, an error, in this case) when this happens?  I'd suggest that you might make the new parameter in step (3) have a name other than `rate`; you might permanently retire the `rate` parameter so that you can issue the deprecation warning/error forever.
